### ISSUE TITLE
confusing return

### ISSUE THREAD

**Issue by 16isaac89** [ajumal-ashraf-dev/react-native-pdf-to-image#2] opened 2021-02-16 10:09 UTC
it returns 
{"_U": 0, "_V": 0, "_W": null, "_X": null}
["/data/user/0/com.uuza/cache/1613469418104_pdf.png

**Comment by kfernandes29** [comment] 2021-03-30 16:34
It's a promise. You need to await the result.

**Comment by ajumal-ashraf-dev** [comment] 2021-11-19 08:01
Closing this issue as it is not a bug

**Closed as completed by ajumal-ashraf-dev** 2021-11-19 08:01 UTC
